name: Doxygen

on:
  workflow_run:
    workflows:
      - CMake
    branches:
      - master
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Git setup
        run: |
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"

      - name: Generate document using Doxygen
        uses: mattnotmitt/doxygen-action@v1.9.5

      - name: Switch git branch to gh-pages and pull if remote exists, then commit and push
        run: |
          git checkout --orphan gh-pages
          git rm -rf .
          mv docs docs_
          git fetch origin gh-pages; isexists=$?
          if [ $isexists -ne 128 ]; then
            git pull origin gh-pages
          fi
          ls -la
          mv docs_ docs
          git add -f docs
          rm -rf docs_
          if [ ! -e .nojekyll ]; then
              touch .nojekyll
              git add .nojekyll
          fi
          git diff --quiet && git diff --staged --quiet || git commit -am "[Update] documents"
          git push origin gh-pages
