name: unittest

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  test-pc:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: configure
        run: |
          mkdir build
          cd build
          cmake .. -DCOLLECTION2_BUILD_TESTS=ON

      - name: build
        working-directory: ${{github.workspace}}/build
        run: cmake --build .

      - name: test
        working-directory: ${{github.workspace}}/build
        run: ctest

  test-avr:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        mcu:
          - "atmega328p"
          - "atmega2560"

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: setup git
        run: |
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"

      - name: setup arduino-cli
        run: |
          mkdir -p ~/arduino-cli
          curl -fsSL https://raw.githubusercontent.com/arduino/arduino-cli/master/install.sh | BINDIR=~/arduino-cli sh
          ~/arduino-cli/arduino-cli core install arduino:avr

      - name: setup QEMU
        run: sudo apt-get -y install qemu-system

      - name: clone AVR toolchain
        run: git clone https://github.com/Enchan1207/cmake-avr ~/cmake-avr

      - name: configure for ${{matrix.mcu}}
        run: |
          mkdir build
          cd build
          cmake .. -DCOLLECTION2_BUILD_TESTS=ON -DAVR_MCU=${{matrix.mcu}} --toolchain=~/cmake-avr/cmake/avr_toolchain.cmake

      - name: build
        working-directory: ${{github.workspace}}/build
        run: cmake --build .

      - name: test
        working-directory: ${{github.workspace}}/build
        run: ctest
